2024-05-23 18:06:58,030 INFO    StreamThr :91558 [internal.py:wandb_internal():85] W&B internal server running at pid: 91558, started at: 2024-05-23 18:06:58.029964
2024-05-23 18:06:58,034 DEBUG   HandlerThread:91558 [handler.py:handle_request():158] handle_request: status
2024-05-23 18:06:58,037 INFO    WriterThread:91558 [datastore.py:open_for_write():87] open: /home/mhm/workspace/Competition_TaxingAI/wandb/run-20240523_180658-tze8adr6/run-tze8adr6.wandb
2024-05-23 18:06:58,037 DEBUG   SenderThread:91558 [sender.py:send():378] send: header
2024-05-23 18:06:58,042 DEBUG   SenderThread:91558 [sender.py:send():378] send: run
2024-05-23 18:06:58,689 INFO    SenderThread:91558 [dir_watcher.py:__init__():211] watching files in: /home/mhm/workspace/Competition_TaxingAI/wandb/run-20240523_180658-tze8adr6/files
2024-05-23 18:06:58,689 INFO    SenderThread:91558 [sender.py:_start_run_threads():1123] run started: tze8adr6 with start time 1716458818.029608
2024-05-23 18:06:58,697 DEBUG   HandlerThread:91558 [handler.py:handle_request():158] handle_request: check_version
2024-05-23 18:06:58,698 DEBUG   SenderThread:91558 [sender.py:send_request():405] send_request: check_version
2024-05-23 18:06:58,908 DEBUG   HandlerThread:91558 [handler.py:handle_request():158] handle_request: run_start
2024-05-23 18:06:58,915 DEBUG   HandlerThread:91558 [system_info.py:__init__():26] System info init
2024-05-23 18:06:58,915 DEBUG   HandlerThread:91558 [system_info.py:__init__():41] System info init done
2024-05-23 18:06:58,915 INFO    HandlerThread:91558 [system_monitor.py:start():194] Starting system monitor
2024-05-23 18:06:58,916 INFO    HandlerThread:91558 [system_monitor.py:probe():214] Collecting system info
2024-05-23 18:06:58,916 INFO    SystemMonitor:91558 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-05-23 18:06:58,917 INFO    SystemMonitor:91558 [interfaces.py:start():188] Started cpu monitoring
2024-05-23 18:06:58,918 INFO    SystemMonitor:91558 [interfaces.py:start():188] Started disk monitoring
2024-05-23 18:06:58,920 INFO    SystemMonitor:91558 [interfaces.py:start():188] Started gpu monitoring
2024-05-23 18:06:58,922 INFO    SystemMonitor:91558 [interfaces.py:start():188] Started memory monitoring
2024-05-23 18:06:58,924 INFO    SystemMonitor:91558 [interfaces.py:start():188] Started network monitoring
2024-05-23 18:06:59,698 INFO    WriterThread:91558 [datastore.py:close():296] close: /home/mhm/workspace/Competition_TaxingAI/wandb/run-20240523_180658-tze8adr6/run-tze8adr6.wandb
2024-05-23 18:06:59,902 INFO    SenderThread:91558 [sender.py:finish():1545] shutting down sender
2024-05-23 18:06:59,903 INFO    SenderThread:91558 [dir_watcher.py:finish():358] shutting down directory watcher
2024-05-23 18:07:00,690 INFO    SenderThread:91558 [dir_watcher.py:finish():388] scan: /home/mhm/workspace/Competition_TaxingAI/wandb/run-20240523_180658-tze8adr6/files
2024-05-23 18:07:00,690 INFO    SenderThread:91558 [dir_watcher.py:finish():402] scan save: /home/mhm/workspace/Competition_TaxingAI/wandb/run-20240523_180658-tze8adr6/files/config.yaml config.yaml
2024-05-23 18:07:00,690 INFO    SenderThread:91558 [file_pusher.py:finish():169] shutting down file pusher
2024-05-23 18:07:00,690 INFO    SenderThread:91558 [file_pusher.py:join():175] waiting for file pusher
2024-05-23 18:07:02,171 INFO    wandb-upload_0:91558 [upload_job.py:push():130] Uploaded file /home/mhm/workspace/Competition_TaxingAI/wandb/run-20240523_180658-tze8adr6/files/config.yaml
2024-05-23 18:07:02,693 INFO    SenderThread:91558 [file_stream.py:finish():601] file stream finish called
2024-05-23 18:07:03,065 INFO    SenderThread:91558 [file_stream.py:finish():605] file stream finish is done
2024-05-23 18:07:03,066 ERROR   StreamThr :91558 [internal.py:wandb_internal():173] Thread HandlerThread:
Traceback (most recent call last):
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 48, in run
    self._run()
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 99, in _run
    self._process(record)
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/sdk/internal/internal.py", line 278, in _process
    self._hm.handle(record)
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/sdk/internal/handler.py", line 150, in handle
    handler(record)
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/sdk/internal/handler.py", line 160, in handle_request
    handler(record)
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/sdk/internal/handler.py", line 702, in handle_request_run_start
    self._system_monitor.probe(publish=True)
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/sdk/internal/system/system_monitor.py", line 217, in probe
    k: v for d in [asset.probe() for asset in self.assets] for k, v in d.items()
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/sdk/internal/system/system_monitor.py", line 217, in <listcomp>
    k: v for d in [asset.probe() for asset in self.assets] for k, v in d.items()
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu.py", line 395, in probe
    info["gpu"] = pynvml.nvmlDeviceGetName(pynvml.nvmlDeviceGetHandleByIndex(0))  # type: ignore
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/vendor/pynvml/pynvml.py", line 1962, in wrapper
    return res.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte
