2024-05-23 18:07:46,082 INFO    StreamThr :92213 [internal.py:wandb_internal():85] W&B internal server running at pid: 92213, started at: 2024-05-23 18:07:46.081811
2024-05-23 18:07:46,087 DEBUG   HandlerThread:92213 [handler.py:handle_request():158] handle_request: status
2024-05-23 18:07:46,088 INFO    WriterThread:92213 [datastore.py:open_for_write():87] open: /home/mhm/workspace/Competition_TaxingAI/wandb/run-20240523_180746-vz4qp2ua/run-vz4qp2ua.wandb
2024-05-23 18:07:46,089 DEBUG   SenderThread:92213 [sender.py:send():378] send: header
2024-05-23 18:07:46,092 DEBUG   SenderThread:92213 [sender.py:send():378] send: run
2024-05-23 18:07:46,923 INFO    SenderThread:92213 [dir_watcher.py:__init__():211] watching files in: /home/mhm/workspace/Competition_TaxingAI/wandb/run-20240523_180746-vz4qp2ua/files
2024-05-23 18:07:46,923 INFO    SenderThread:92213 [sender.py:_start_run_threads():1123] run started: vz4qp2ua with start time 1716458866.081052
2024-05-23 18:07:46,932 DEBUG   HandlerThread:92213 [handler.py:handle_request():158] handle_request: check_version
2024-05-23 18:07:46,933 DEBUG   SenderThread:92213 [sender.py:send_request():405] send_request: check_version
2024-05-23 18:07:47,112 DEBUG   HandlerThread:92213 [handler.py:handle_request():158] handle_request: run_start
2024-05-23 18:07:47,119 DEBUG   HandlerThread:92213 [system_info.py:__init__():26] System info init
2024-05-23 18:07:47,119 DEBUG   HandlerThread:92213 [system_info.py:__init__():41] System info init done
2024-05-23 18:07:47,120 INFO    HandlerThread:92213 [system_monitor.py:start():194] Starting system monitor
2024-05-23 18:07:47,120 INFO    HandlerThread:92213 [system_monitor.py:probe():214] Collecting system info
2024-05-23 18:07:47,120 INFO    SystemMonitor:92213 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-05-23 18:07:47,122 INFO    SystemMonitor:92213 [interfaces.py:start():188] Started cpu monitoring
2024-05-23 18:07:47,124 INFO    SystemMonitor:92213 [interfaces.py:start():188] Started disk monitoring
2024-05-23 18:07:47,126 INFO    SystemMonitor:92213 [interfaces.py:start():188] Started gpu monitoring
2024-05-23 18:07:47,127 INFO    SystemMonitor:92213 [interfaces.py:start():188] Started memory monitoring
2024-05-23 18:07:47,129 INFO    SystemMonitor:92213 [interfaces.py:start():188] Started network monitoring
2024-05-23 18:07:47,933 INFO    WriterThread:92213 [datastore.py:close():296] close: /home/mhm/workspace/Competition_TaxingAI/wandb/run-20240523_180746-vz4qp2ua/run-vz4qp2ua.wandb
2024-05-23 18:07:48,106 INFO    SenderThread:92213 [sender.py:finish():1545] shutting down sender
2024-05-23 18:07:48,106 INFO    SenderThread:92213 [dir_watcher.py:finish():358] shutting down directory watcher
2024-05-23 18:07:48,924 INFO    SenderThread:92213 [dir_watcher.py:finish():388] scan: /home/mhm/workspace/Competition_TaxingAI/wandb/run-20240523_180746-vz4qp2ua/files
2024-05-23 18:07:48,924 INFO    SenderThread:92213 [dir_watcher.py:finish():402] scan save: /home/mhm/workspace/Competition_TaxingAI/wandb/run-20240523_180746-vz4qp2ua/files/config.yaml config.yaml
2024-05-23 18:07:48,925 INFO    SenderThread:92213 [file_pusher.py:finish():169] shutting down file pusher
2024-05-23 18:07:48,925 INFO    SenderThread:92213 [file_pusher.py:join():175] waiting for file pusher
2024-05-23 18:07:49,768 INFO    wandb-upload_0:92213 [upload_job.py:push():130] Uploaded file /home/mhm/workspace/Competition_TaxingAI/wandb/run-20240523_180746-vz4qp2ua/files/config.yaml
2024-05-23 18:07:50,427 INFO    SenderThread:92213 [file_stream.py:finish():601] file stream finish called
2024-05-23 18:07:50,863 INFO    SenderThread:92213 [file_stream.py:finish():605] file stream finish is done
2024-05-23 18:07:50,864 ERROR   StreamThr :92213 [internal.py:wandb_internal():173] Thread HandlerThread:
Traceback (most recent call last):
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 48, in run
    self._run()
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 99, in _run
    self._process(record)
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/sdk/internal/internal.py", line 278, in _process
    self._hm.handle(record)
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/sdk/internal/handler.py", line 150, in handle
    handler(record)
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/sdk/internal/handler.py", line 160, in handle_request
    handler(record)
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/sdk/internal/handler.py", line 702, in handle_request_run_start
    self._system_monitor.probe(publish=True)
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/sdk/internal/system/system_monitor.py", line 217, in probe
    k: v for d in [asset.probe() for asset in self.assets] for k, v in d.items()
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/sdk/internal/system/system_monitor.py", line 217, in <listcomp>
    k: v for d in [asset.probe() for asset in self.assets] for k, v in d.items()
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu.py", line 395, in probe
    info["gpu"] = pynvml.nvmlDeviceGetName(pynvml.nvmlDeviceGetHandleByIndex(0))  # type: ignore
  File "/home/mhm/anaconda3/envs/taxingai-venv/lib/python3.9/site-packages/wandb/vendor/pynvml/pynvml.py", line 1962, in wrapper
    return res.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte
